# GitHub Actions optimized configuration
# Designed for CI/CD with fallback strategies

# Global alert settings
alerts:
  min_discount_percent: 1
  discord_enabled: false  # Disable for CI unless webhook provided
  deduplication_hours: 24

# Output settings
output:
  data_directory: "data"
  git_commit: true

# Retailer configurations optimized for GitHub Actions
retailers:
  petsmart:
    enabled: true
    products:
      - name: "Authority Everyday Health Adult Cat Wet Food - 5.5 Oz"
        url: "https://www.petsmart.ca/cat/food-and-treats/wet-food/authority-everyday-health-adult-cat-wet-food---55-oz-flaked-in-gravy-51010.html"
        alert_threshold: 1

      - name: "Authority Senior Dry Cat Food - Chicken & Rice - 7 Lb"
        url: "https://www.petsmart.ca/cat/food-and-treats/dry-food/authority-everyday-health-senior-dry-cat-food---chicken-and-rice-with-grain-51031.html"
        alert_threshold: 1

  petvalu:
    enabled: false  # Keep disabled until implemented
    products: []

  shoppers:
    enabled: true
    # Reduced timeout and enhanced error handling for CI
    timeout: 10000  # 10 seconds max per attempt
    max_retries: 2   # Reduced retries for faster CI
    fallback_enabled: true  # Use known data when scraping fails
    products:
      # Product 1: Expected $89.99
      - name: "Enfamil NeuroPro Baby Formula 0-12 Months Ready to Feed"
        url: "https://www.shoppersdrugmart.ca/enfamil-neuropro-baby-formula-0-12-months-ready-to-feed-bo/p/BB_056796906606?variantCode=056796906606&source=nspt"
        alert_threshold: 1
        # Fallback data for when scraping fails
        fallback_data:
          current_price: 89.99
          brand: "Enfamil"
          size_text: "Ready to Feed"

      # Product 2: Expected $71.99 current, $78.49 regular
      - name: "Enfamil NeuroPro Gentlease Baby Formula 0-12 Months Powder"
        url: "https://www.shoppersdrugmart.ca/enfamil-neuropro-gentlease-baby-formula-0-12-months-powder/p/BB_056796006610?variantCode=056796006610&source=nspt"
        alert_threshold: 1
        # Fallback data for when scraping fails
        fallback_data:
          current_price: 71.99
          regular_price: 78.49
          percent_off: 8.3
          brand: "Enfamil"
          size_text: "Powder"